### ISSUE TITLE
High memory and CPU usage

### ISSUE THREAD

**Issue by dotdash** [zxqfl/TabNine#43] opened 2018-12-20 04:28 UTC
While working on rustc, I noticed TabNine and rls regularly consuming 100% CPU each for quite a while. I usually only notice it when I switch to a different virtual desktop when I build rustc, so it's not only while actually working in vim, but also(?) a while after I stop changing things.

Additionally, the memory usage for TabNine is _huge_. Currently top shows:

`23316 doener    20   0 9964048   4,9g      0 S   0,0  31,2  74:41.38 TabNine`

The process was started about 86 hours ago.

**Comment by zxqfl** [comment] 2018-12-20 08:44
Does it continue after the build stops? This is possibly caused by TabNine picking up all the filesystem events from the build.

That's a lot of memory, a normal amount of usage is 500MB-1GB. Does it go back to a more reasonable level if you restart your editor or type TabNine::restart?

**Comment by DoronCohen** [comment] 2019-01-06 08:50
I have this issue when checking out between versions while working on Python. when the versions are very different from each other I assume TabNine is rebuilding it's DB but the CPU usage is insane making my laptop almost unusable.

It would be very convenient to have a CPU / RAM limit configuration

**Comment by ovidiucs** [comment] 2019-01-24 16:49
![image](https://user-images.githubusercontent.com/2406691/51693722-2e4aec00-2008-11e9-976c-63e6adbc8f9c.png)
This is on archlinux.

**Comment by taylorlapeyre** [comment] 2019-02-20 00:30
Using over 3GB of memory on my machine:

<img width="380" alt="screen shot 2019-02-19 at 4 30 19 pm" src="https://user-images.githubusercontent.com/1610503/53057296-a79cf980-3463-11e9-928f-b5a7e834c9f9.png">

**Comment by tommoor** [comment] 2019-02-20 22:52
I love the functionality TabNine brings, but having to uninstall until this issue is somewhat resolved 😢 

![image](https://user-images.githubusercontent.com/380914/53130431-13906800-351f-11e9-8e9f-f8bb2707f4fc.png)

**Comment by taylorlapeyre** [comment] 2019-02-26 18:39
@zxqfl Hey there! I was wondering if you have any updates on whether this is something you are working on, something you are currently fixing, or if this is more of a "no fix" kind of situation.

As a paying customer, I just want to know all the facts!

**Comment by n3bulous** [comment] 2019-03-06 19:52
Same issue here re: memory. 3G for a fairly small java/groovy project.

**Comment by Deewiant** [comment] 2019-03-13 13:29
A fairly simple, though heavy, test case for both this and #24 (they seem like the same issue to me) is OpenWrt. I did a clean checkout of current master (commit `2407b1edccc2f2d426333bd7cc1743c8e4da8dbd`) there and ran TabNine manually, asking it for one completion in the OpenWrt source directory, as follows (I pieced this together based on company-tabnine, is there API documentation somewhere?):

```
$ ./TabNine
{"version": "0.11.1", "request": {"Autocomplete": {"filename": "/path/to/openwrt/Makefile", "before": "hi", "after": "", "region_includes_beginning": false, "region_includes_end": false, "max_num_results": 10}}}
{"suffix_to_substitute":"hi","results":[],"promotional_message":[]}
```

I left it hanging there since I just needed to point it to the OpenWrt directory.

This gave me 100% CPU usage for eight seconds to start with, which is fair enough since it's indexing the whole directory for the first time. Memory usage stabilizes at around 300 megabytes (looking at the "RES" column in `htop`). Then I followed up with building OpenWrt in another shell, using the default configuration because that suffices to exhibit this issue, and with eight CPU cores to make it not take forever (and `nice -n19` because I wanted the rest of my system to not suffer too much):

```sh
make defconfig
nice -n19 make world -j8
```

For some background, OpenWrt is a Linux distribution for embedded devices — routers in particular. Its build system first builds "tools", which include basic things like `tar` and `sed`, then the "toolchain" i.e. `gcc` and company, before it goes on to actually build the whole system.

Of TabNine, I can observe all of the following during even just the "tools" build:

* Memory usage growing above 1000 megabytes
* CPU usage hovering around 10–40% but occasionally spiking as high as 300%
* A peek at `strace` showing that TabNine is doing all kinds of stuff including calling `inotify_add_watch` in the `build_dir` directory, which I should note is under `.gitignore`

After the "toolchain" build completes, memory usage is at almost 2500 megabytes and user CPU time (as shown by `htop`) is at about 19 minutes. Since the build has taken around 30 minutes so far, this is over 60% average CPU usage.

In the end, the entire build took me just shy of 44 minutes. At that point TabNine's CPU time stabilized at 40 minutes and memory usage at nearly 4500 megabytes. I think it's fair to call both of these "high usage". Normally at this point I'd `pkill TabNine` until it bloats up again, but sometimes I've missed it until it's grown to eat so many gigabytes that it's actually causing trouble for the rest of my system.

This time I also took a look at the number of inotify watches TabNine has registered:

```sh
$ grep -c inotify /proc/27260/fdinfo/7
27118
```

That definitely seems incorrect. Based on this and what I saw with `strace`, I'd wager that there's a bug related to processing of `.gitignore` and similar files: If an entire directory is ignored, I don't think TabNine should be recursing into it and especially not adding inotify watches therein. That might be the sole cause of both the CPU and the memory usage.

**Comment by zxqfl** [comment] 2019-03-13 18:57
Thank you for the detailed investigation and analysis. Indeed, TabNine places a watch on every subdirectory, even those which match patterns in `.gitignore`. This is because the library which TabNine uses to watch directories ([notify](https://github.com/passcod/notify)) and the library which it uses to identify ignored paths ([ignore](https://docs.rs/ignore/0.4.6/ignore/)) are different.

I guess the best way to fix this issue will be for TabNine to still use `ignore`, but to handle recursing into sub-directories itself, allowing it to avoid recursing into `.gitignore`d directories.

PS: You can find API documentation [here](https://github.com/zxqfl/TabNine/blob/master/HowToWriteAClient.md).

**Comment by zxqfl** [comment] 2019-05-16 02:05
I reproduced the high memory usage when building OpenWrt. Today I released an update to TabNine which uses 0% CPU while building OpenWrt. The new behaviour is as follows:

- TabNine initially places a recursive watch on the project root.
- Whenever TabNine receives a change notification for an ignored path and the notification comes from a recursive watch on a path P, the recursive watch on P is replaced with a non-recursive watch on P and a recursive watch on all non-ignored immediate children of P.

The update is currently available to beta testers. To try it, type `TabNine::become_beta_tester`, then type `TabNine::version` to check you have the new version -- the new version number is 1.0.14.

If no beta testers report issues, I'll release it to all users soon.

Thanks again for investigating!

**Comment by zxqfl** [comment] 2019-05-16 21:10
Closing for now, please re-open if the problem persists.

**Closed** 2019-05-16 21:10 UTC

**Comment by superDuperCyberTechno** [comment] 2019-09-02 09:06
2.1.17 is consuming 3.3 GB of memory (and counting), ~35% CPU. Been running for an hour or so.

**Comment by sgvazy** [comment] 2019-09-03 07:14
![tabnine](https://user-images.githubusercontent.com/34510328/64151609-57184700-ce5d-11e9-86d3-26c5602d4682.png)
v2.1.11 uses too much memory

**Comment by moritz** [comment] 2019-09-08 11:34
Can confirm, tabnine 2.1.17 with vim consumes several GB if I leave it open with a few python tabs.

Some of my python projects contains `venv` directories with virtualenvs that contain quite a few python files, no idea if this related.

@zxqfl please reopen, or should I open a new bug?

**Comment by QLaille** [comment] 2019-09-17 17:32
Problem is persisting with TN taking 20% of my RAM at start, and can go up to soft-locking the PC after 45 minutes or so. Fortunately my Fan runs like crazy when I'm close to 100% resources used. 
Version 2.1.11 for VSCode.

**Comment by doggyeh** [comment] 2019-09-19 10:11
You can switch to old version which doesn't have this problem for now.
For example, I'm using vim. 
git clone https://github.com/zxqfl/tabnine-vim ~/.vim/bundle
cd ~/.vim/bundle/tabnine-vim
git checkout c20d73f3e007d4b8804c344f114eb03b5c9466a3

This version doesn't have the CPU/MEM problem for me.

**Comment by ilAYAli** [comment] 2019-09-19 10:40
I just checked `top` on my development machine (v. 2.1.17):
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
32001 petter    20   0   20.4g  20.0g  11400 S 175.8  63.8 276:55.62 TabNine
```
20GB resident memory(!)

**Comment by QLaille** [comment] 2019-09-20 08:20
> You can switch to old version which doesn't have this problem for now.
> For example, I'm using vim.
> git clone https://github.com/zxqfl/tabnine-vim ~/.vim/bundle
> cd ~/.vim/bundle/tabnine-vim
> git checkout c20d73f3e007d4b8804c344f114eb03b5c9466a3
> 
> This version doesn't have the CPU/MEM problem for me.

I'll see what I can do with VSC (sorry, not very fond of vim :p ) and keep you in touch

**Comment by QLaille** [comment] 2019-09-29 16:11
I can confirm that TabNine V2.1.7 is stable on VSCode and doesn't take a whole lot of resources.

**Comment by validatedev** [comment] 2019-10-03 09:54
TabNine 2.1.17 uses 1.5 GB of the memory at the initial. Is this the expected behaviour? Isn't it so much?

**Comment by CDitzel** [comment] 2019-10-08 13:37
using TabNine within emacs and the company package leads to an initial memory usage of 3 GB

**Comment by shamoons** [comment] 2019-11-11 13:53
How do I downgrade to 2.1.17 with VS Code (windows WSL)

**Comment by VinSpee** [comment] 2019-11-21 16:04
Hi! I hit an all-time record this morning:

![44GB memory](https://user-images.githubusercontent.com/582828/69354461-22db4800-0c4e-11ea-9091-cb38745ada84.png)

**Comment by moritz** [comment] 2019-11-21 16:33
@zxqfl could you please re-open this issue? It still seems to be a problem for a lot of people (me included).

**Comment by tmpm697** [comment] 2019-11-28 04:30
auto completion that took roughly 10GB when perform is not cool. will try later :)

**Comment by Seybo** [comment] 2019-12-03 15:27
![image](https://user-images.githubusercontent.com/10584167/70064396-79159700-160f-11ea-86b8-1d7798148c2a.png)

**Comment by muke5hy** [comment] 2019-12-19 18:29
Uninstalling, it is taking 26+ GB of ram 

<img width="520" alt="Screenshot 2019-12-19 at 11 55 15 PM" src="https://user-images.githubusercontent.com/545172/71199252-8e4f1e80-22bb-11ea-8e48-a59800745665.png">

**Comment by adriancoliba** [comment] 2019-12-21 23:26
Has anyone found a solution yet?

**Comment by Shougo** [comment] 2019-12-21 23:30
You can disable Tabnine local feature in Tabnine::config

**Comment by salanhess** [comment] 2019-12-27 02:28
TabNine::version 2.1.22 still use more than 1GB memory

**Comment by sQVe** [comment] 2019-12-27 06:27
@salanhess Yes. Disable TabNine Local.

**Comment by salanhess** [comment] 2019-12-27 06:28
> git checkout c20d73f3e007d4b8804c344f114eb03b5c9466a3

Thx very much, this version only take 500M mem!

**Comment by Arstman** [comment] 2020-01-02 08:30
on my ubuntu vps server, i use the vim-tabnine plugin, and today i can not connect to my vps via mosh, after reboot and testing for everything, and turns out it is tabnine which cost up to 65% memory and 74% of cpu!!!!

I try disable Local as mentions above, it's better but still cost 1.5g of men, while my vps only have 4g in total.

i love Tabnine, but seem now i can only use it in my MBP and have to uninstall from my vps.

hope this issue can be solved soom.

thanks

**Comment by jh0l** [comment] 2020-05-19 17:31
So you're not going to provide an option to adjust the memory usage of tabnine local so as to incentivise people to buy tabnine professional?

**Comment by drorweiss** [comment] 2020-05-19 19:54
@jh0l Actually, the exact opposite is true:
1. We have already introduced a significant reduction in the amount of memory TabNine consumes
2.  we are actively working on a lightweight model that will be available as a part of the free plan and will consume much less memory. Just to be clear, the TabNine memory requirements are derived from the inherent memory consumption of a large neural model.
3.  TabNine Professional provides superior code prediction thanks to the GPUs in our cloud servers- this, regardless of memory, is a pretty compelling reason to upgrade!

**Comment by jh0l** [comment] 2020-05-19 20:03
Ok I can totally understand that then. Apologies if I seemed at all accusatory, I wasn't aware of how exactly the memory consumption works with your... neural models. I'll try upgrading then!

**Comment by drorweiss** [comment] 2020-05-19 20:10
No worries, thanks @jh0l 
We have a free trial for TabNine Pro - don't forget to enter the API key you get and enable TabNine cloud. If memory consumption is high, you may choose to disable TabNine Local.

**Comment by theonlygusti** [comment] 2020-08-02 19:46
TabNine still has huuuuuge CPU usage if I am typing a lot quickly. It consistently whirrs up my laptop's fans in a few moments.

**Comment by buraksakalli** [comment] 2020-08-04 11:16
Too high memory usage on my W10 device. I disabled `TabNine Local` as well.
![tabnine](https://user-images.githubusercontent.com/10114716/89287554-e117f380-d65c-11ea-94ea-b134cdc1918f.png)

**Comment by kahveciderin** [comment] 2020-08-05 06:20
Excessive memory usage on my linux mint 20 machine. I am experiencing sudden crashes every two hour or so.

**Comment by Picoseconds** [comment] 2020-08-15 22:54
The memory usage is too high and I get BSOD. Please fix this because your extension is too useful for me. TabNine.exe takes up even more memory than Chromium!

**Comment by dialguiba** [comment] 2020-09-07 05:04
![image](https://user-images.githubusercontent.com/52766986/92350131-9fd09480-f09d-11ea-97bf-a3bb074d4833.png)
Same here :(

**Comment by charlie0077** [comment] 2020-10-11 19:05
I had to uninstall tabnine because of of this. I usually have more than 6 vscode project open. 6*2G = 12G.

**Comment by mkubdev** [comment] 2020-10-12 16:04
Excessive memory usage on Windows 10 with VSCode's extension.. ~1/1.5G. I'm not experiencing any crash and BSOD but it's too heavy to use..

**Comment by lvfxbr** [comment] 2020-10-15 13:55
Why is 1GB of usage in the first place? Could we limit it like max_memory_usage = 512M or max_cpu_usage=20% keeping performance?

**Comment by Picoseconds** [comment] 2020-10-15 20:24
AI uses a lot of memory.

**Comment by solidstatejake** [comment] 2020-10-20 21:19
I really like Tabnine. It allows vscode to function like an IntelliJ-based IDE, but I can’t even press tab for autocomplete (i.e. Emmet), or manually format my code when it’s on.

**Comment by RenanFG** [comment] 2020-10-22 18:01
same, at project start already 1gb memory, after 200 lines of code 1.5gb..

**Comment by mkhasson97** [comment] 2020-11-26 12:44
Same problem!, Tabnine uses a lot of RAM

**Comment by AkdenizKutayOcal** [comment] 2020-11-27 10:06
I love the VSCode extension but it is already consuming 1.5G after 100 lines of code. I hope it will be fixed at some point.

**Comment by WilliamD47** [comment] 2021-02-03 11:08
Still an issue in 2021; using 2GB ram on a python project with a couple hundred lines of code. I'm using a mac

**Comment by asheroto** [comment] 2021-02-18 04:15
High memory issues occur on my machine too. Language agnostic. It's the highest memory consuming process on my computer.  Ha!

**Comment by Philwi** [comment] 2021-02-18 13:04
Got some huge amount of memory consumption as well. Will uninstall until its fixed...

**Comment by ahmad-ali14** [comment] 2021-03-22 10:00
same here, it's almost passing Google chrome with 20 open tabs. 
https://i.imgur.com/dRbBUQM.png

**Comment by multiwebinc** [comment] 2021-04-14 20:05
Why is this issue closed if it's obviously still a problem.

**Comment by Limatucano** [comment] 2021-06-10 13:37
I also have this problem, but for me it's more controlled
![image](https://user-images.githubusercontent.com/38586541/121534546-b19dea00-c9d7-11eb-86e9-67602d3cb2a1.png)

Has anyone found the solution?

**Comment by mkubdev** [comment] 2021-06-11 12:45
@Limatucano I was struggling at 1gb / 1.5gb. I'm at 500mb like you now. For me it's a good improvment...

**Comment by ruv** [comment] 2021-06-17 08:31
A possible workaround is to limit the memory (and maybe CPU) for the editor and all its sub-processes (i.e., for the process tree).

In Windows, something like [Process Governor](https://github.com/lowleveldesign/process-governor) can be used.

**Comment by asheroto** [comment] 2021-06-19 06:58
Indeed that is a workaround, but this is absolutely an issue within TabNine.  There are numerous reports of this problem, and even after reinstalling Windows the issue persists.

**Comment by Limatucano** [comment] 2021-06-20 12:43
Yeah, we dont need to find a workaround, because they need to resolve this issue. And i dont understand why this issue its closed

**Comment by mkubdev** [comment] 2021-06-21 13:53
Is ~500mo too much for you guys ? @2020 we struggled with 1,5Gb... 500 is fine.

**Comment by ilAYAli** [comment] 2021-06-21 14:07
500MB? I gave up on the plugin when it used > 20GB of resident RAM!
The RAM usage is probably proportional to the size of the indexed code and available RAM.

**Comment by mkubdev** [comment] 2021-06-21 14:21
@ilAYAli Yes! I'm running VSCode from WSL2 and i have no problem anymore with TabNine ! To be honest, I don't know if this is optimization from codata, or it's because recently add a memory limitation on my WSL2 instance...

To add memory limitation to $wsl2 : 
1. Create a file at `%UserProfile%/.wslconfig`
2. Set config :
```
[wsl2]
memory=6GB # Limits VM memory in WSL 2 to 6 GB
/*processors=5 # Makes the WSL 2 VM use two virtual processors*/
```

![2](https://user-images.githubusercontent.com/50140834/122777340-3b896500-d2ac-11eb-87ec-ee1705e0d66d.JPG)

**Comment by asheroto** [comment] 2021-06-22 00:58
@mkubdev your WSL instance is a Windows-based one?

**Comment by talcodota** [comment] 2021-06-22 11:35
> 500MB? I gave up on the plugin when it used > 20GB of resident RAM!
> The RAM usage is probably proportional to the size of the indexed code and available RAM.

Hey @ilAYAli, 
This should never happen.
Can you please share your logs, so we can investigate this?
type _tabnine::logs_ inside your IDE and send us the log files to [support@tabnine.com](url)
Also, name the IDE and the operating system you are using.

Thank you.

**Comment by ilAYAli** [comment] 2021-06-22 15:02
@talcodota  thank you for your feedback, but I am not using the plugin anymore.
It is even possible that the problem is solved as it is quite some time since I used it (6+ months).
It was not an IDE, but vim or neovim on a Linux development server.

**Comment by eo1989** [comment] 2021-08-20 14:04
Has this crap been resolved? I had to remove t9 from my neovim workflow because it was making the entire mac unusable. It was the newest version available. masOS 10.15.7.

**Comment by MatiasEsf** [comment] 2021-09-11 15:34
![Captura](https://user-images.githubusercontent.com/49958478/132953187-421fc946-0a24-4815-87e0-08a95a6618b2.PNG)

my tabnine uses too much cpu, although little ram memory, the extension is great, but it has this little great detail

**Comment by asheroto** [comment] 2021-09-23 06:54
@zxqfl @dimacodota @YotamFromCodota

**Comment by ET-CS** [comment] 2021-09-26 09:59
Killed my computer :(

![image](https://user-images.githubusercontent.com/1791696/134803119-ee64cb2f-2f59-48b9-863f-7aee9b42ab31.png)

I have to uninstall until this is resolved

**Comment by paulologeh** [comment] 2021-12-09 10:26
i also have the same issue. Using over 1GB of memory on my mac.

**Comment by evanerwee01** [comment] 2022-03-15 03:06
I also have the same issue. Have to uninstall until the issue is fixed on Windows. I have advice my entire team to remove TabNine from PyCharm. We all have the same issue.

**Comment by iver0** [comment] 2022-04-21 05:24
Same here with Doom Emacs on Ubuntu, it eats all the CPU causing the editor to stutter heavily, completely unusable...

**Comment by asheroto** [comment] 2022-06-15 11:40
Hm.... 250+ days ago I posted on this thread of now-53 participants. Sadly due to the ongoing and widespread issues I was forced to abandon TabNine. :-/

**Comment by beceluiz** [comment] 2022-09-06 15:42
![image](https://user-images.githubusercontent.com/97623324/188678079-6653880b-e6f3-402d-918c-f71882c5cd8f.png)

i'm with the same problem on windows

**Comment by martentamm** [comment] 2022-09-07 09:29
Same issue

**Comment by Pablo-hub44** [comment] 2022-09-22 17:36
sameee issue

**Comment by mkubdev** [comment] 2022-09-23 10:40
> @mkubdev your WSL instance is a Windows-based one?

Sorry for the 1 year reply lol. Yes windows based one. It's Windows Sub-System Linux.

**Comment by yeukfei02** [comment] 2022-11-02 09:38
on macbook pro 16 inch, macos version 12.6.1..it seems the same issue
use a lot of CPU and memory...

I use vscode...

does it fixed?

**Comment by Haagimus** [comment] 2022-12-05 22:25
Still happening for me too.
| Name | Version |
|-|-|
| OSX | 13.0.1 (22A400) |
| VSCode | 1.73.1 |
| Tabnine | 3.6.31 (latest) |

no .gitignore for my project which currently consists of a single main.py and one folder with nothing in it. There is no good reason for this to be happening with basically no load at all on it.

**Comment by devondr** [comment] 2023-01-21 12:31
My development computer has around 8gbs, Tabnine was using around 4gbs of RAM and basically it made it crash

**Comment by mantorbe** [comment] 2023-05-18 14:56
I have the same Issue with Linux Debian 10, using Pycharm... Great pluggin, but kill the machine performance!

**Comment by rooiratel** [comment] 2023-09-12 18:25
@zxqfl can this issue be reopened? People have been having the same issue for 4 years since this was closed.

**Comment by alex-dokienko** [comment] 2023-11-24 09:44
same for me, it using cpu and memory as crazy, causing my m1 mac heating which I already forgot how is that (especially as it's not giving fan noise) it's become problem as eventually it just cause whole mac OS to crash

**Comment by FalcoGer** [comment] 2023-12-11 13:06
Having the same issue. Whenever I start vim, memory and cpu usage shoots through the roof, causing swapping and the system crawls to a halt. It usually provides it's completions just fine and without too much overhead, but sometimes it just goes crazy.
